
version: 2.1

jobs:
  compile_maven:
    docker:
      - image: maven:3.9.6-openjdk-17-alpine
    working_directory: ~/my-java-app-project
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
            - maven-deps-

      - run:
          name: "Build With Maven"
          command: "maven clean compile!"

      - save_cache:
          paths:
            - ~/.m2
          key: maven-deps-{{ checksum "pom.xml" }}
workflows:
  say-hello-workflow: 
    jobs:
      - compile_maven
