apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: net-pol
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: demo-app
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            run: client

    - from:
      - podSelector:
          matchLabels:
            app: utilities  

    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: calico-system
        podSelector:
          matchLabels:
            k8s-app: calico-kube-controllers
      # Rule 4: Allow tigera-system namespace on port 8080
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: tigera-operator
        
      ports:
      - protocol: TCP       
        port: 8080